################ Spanish language ##################
[es]
contentDir = "content/spanish"
weight = 1
[es.params]
  label = "Español"
  locale = "es-ar"

################ English language ##################
[en]
contentDir = "content/english"
weight = 2
[en.params]
  label = "English"
  locale = "en-us"

################ Portuguese language ##################
[pt]
contentDir = "content/portuguese"
weight = 3
[pt.params]
  label = "Português"
  locale = "pt-br"
