################ Spanish language ##################
[es]
label = "Español"
locale = "es-ar"
contentDir = "content/spanish"
weight = 1

################ English language ##################
[en]
label = "English"
locale = "en-us"
contentDir = "content/english"
weight = 2

################ Portuguese language ##################
[pt]
label = "Português"
locale = "pt-br"
contentDir = "content/portuguese"
weight = 3
